
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASP.Net_WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BuyingCar
{

    public int Id { get; set; }

    public string DataClient { get; set; }

    public int Cost { get; set; }

    public System.TimeSpan DatePurchase { get; set; }

    public int SellingAutoId { get; set; }



    public virtual SellingAuto SellingAuto { get; set; }

}

}
