//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Net_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entity1()
        {
            this.Entity2 = new HashSet<Entity2>();
        }
    
        public int Id { get; set; }
        public bool Логический { get; set; }
        public string Строковый { get; set; }
        public int Числовой { get; set; }
        public System.TimeSpan ДатаВремя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity2> Entity2 { get; set; }
    }
}
