//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Net_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity2
    {
        public int Id { get; set; }
        public int Числовой { get; set; }
        public string Строковый { get; set; }
    
        public virtual Entity1 Entity1 { get; set; }
    }
}
