
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASP.Net_WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SellingAuto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SellingAuto()
    {

        this.BuyingCar = new HashSet<BuyingCar>();

    }


    public int Id { get; set; }

    public Nullable<bool> InStock { get; set; }

    public string AutoDescription { get; set; }

    public Nullable<int> Cost { get; set; }

    public Nullable<System.DateTime> DateReceipts { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BuyingCar> BuyingCar { get; set; }

}

}
